apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: backend-config
  namespace: bookstore-dev
data:
  NODE_ENV: "development"
  PORT: "3000"
  DB_HOST: "postgresql-service"
  DB_PORT: "5432"
  DB_NAME: "bookstore"
  LOG_LEVEL: "debug"
